### PR TITLE
company-register done, and job

### PR DESCRIPTION
**Pull request by Abdallahman-habyarimana**

### CODE REVIEW

**Review by franklintrinh367 — COMMENTED** [review]
There is a issue for your company-register
Even all the fields are not filled. It still lets you go to the next step
image

**Review by franklintrinh367 — COMMENTED** [review]
And in my opinion, i think service is the place where data are shareable and a point to communicate with backend.
Not a right place to initializeForm

**Review by franklintrinh367 — COMMENTED** [review]
image
This is what i'm talking about when user clicks next

**Comment by Abdallahman-habyarimana** [comment]
Alright I get it

**Comment by franklintrinh367** [comment]
i close this one so you can pull a new one

**Pull request closed without merging**
